[book]
authors = ["s2301089"]
language = "ja"
multilingual = false
src = "src"
title = "Control_General"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/s2301089/"
git-repository-icon = "fa-github"

[preprocessor.image-size]
command = "mdbook-image-size"

[preprocessor.codename]