[env:DigitalOut_LED_blink]
platform = ststm32
board = nucleo_f446re
framework = mbed
build_src_filter = +<gpio/digitalout_led_blink.cpp>

[env:DigitalIn_LED_blink]
platform = ststm32
board = nucleo_f446re
framework = mbed
build_src_filter = +<gpio/digitalin_led_blink.cpp>

[env:PwmOut_LED_blink]
platform = ststm32
board = nucleo_f446re
framework = mbed
build_src_filter = +<timer/pwmout_led_blink.cpp>

[env:AnalogIn_LED_PWM]
platform = ststm32
board = nucleo_f446re
framework = mbed
build_src_filter = +<analog/analogin_led_pwm.cpp>

[env:printf]
platform = ststm32
board = nucleo_f446re
framework = mbed
build_src_filter = +<connectivity/printf.cpp>

[env:serial_printf]
platform = ststm32
board = nucleo_f446re
framework = mbed
build_src_filter = +<connectivity/serial_printf.cpp>

[platformio]
build_cache_dir = .cache